### ISSUE TITLE
Material Camera produces corrupt video with green lines

### ISSUE THREAD

**Issue by ManicMapple** [afollestad/material-camera#10]
Hi,

On the model: Samsung Galaxy S4 - GT-I9505 (android 5.01)  a recorded video only show green lines. Audio is ok. Could it be that is has something to do with http://stackoverflow.com/questions/5826712/android-mediarecorder-produces-corrupt-video-with-green-lines

Edit: The preview while recording is fine, only the output video is corrupt. Here is a preview
![screenshot 735 hhh _ alpha test campus - google chrome](https://cloud.githubusercontent.com/assets/954437/11623555/f6058d7a-9ccd-11e5-8d0f-f3f7713dff07.png)

Thank you

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/pull/16
