### ISSUE TITLE
Allow starting MaterialCamera from a fragment

### ISSUE THREAD

**Issue by amosyuen** [afollestad/material-camera#104]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Camera.
- [x] I have given my issue a non-generic title.

The MaterialCamera constructor only allows an Activity, would be great if it could support a fragment too.

**Comment by mowcixo** [comment]
I've proposed the PR #82 that fixes this.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/releases/tag/0.4.0

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/releases/tag/0.4.1
