### ISSUE TITLE
Setting labelRetry and labelUseVideo do not change the value of the labels

### ISSUE THREAD

**Issue by thierrykoppenol** [afollestad/material-camera#105]
- [X] I have verified there are no duplicate active or recent bugs, questions, or requests
- [X] I have verified that I am using the latest version of Material Camera.
- [X] I have given my issue a non-generic title.

###### Include the following:
 - Material Camera version: `0.3.2`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `Samsung`
 - Device Name: `Galaxy S5 (SM-G900F)`
 
###### Reproduction Steps

1.  Setting .labelRetry("someString") and .labelUseVideo("someString") in code
2. Starting the camera intent and taking a picture / video
3. Check the label below the taken picture / video

![screen shot 2016-09-22 at 11 47 38](https://cloud.githubusercontent.com/assets/22367581/18743717/9cb32ca6-80ba-11e6-9749-c60996fcfa83.png)

###### Expected Result
Labels displaying the strings as set in the methods

###### Actual Result
Labels are showing the default values (Retry and Use Video / Use Stillshot)

![screenshot_2016-09-22-11-51-19](https://cloud.githubusercontent.com/assets/22367581/18743777/e8cdac38-80ba-11e6-8096-609349eb6264.png)

**Comment by mowcixo** [comment]
I guess that's because the 0.3.2 is previous to this changes... try to use the master branch until there's a new tag.

**Comment by thierrykoppenol** [comment]
Thanks, this has fixed the problem!

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/releases/tag/0.4.0

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/releases/tag/0.4.1
