### ISSUE TITLE
Error: Failed to resolve: com.afollestad:easyvideoplayer:0.2.13

### ISSUE THREAD

**Issue by DenisZhuravlev** [afollestad/material-camera#106]
`compile 'com.afollestad:material-camera:0.4.1'`

causing  `Error:Failed to resolve: com.afollestad:easyvideoplayer:0.2.13`

Adding `maven { url "https://dl.bintray.com/drummer-aidan/maven" }` doesn't help

**Comment by mowcixo** [comment]
Yep, that's probably true @afollestad, there is not published 0.2.13 version in bintray https://dl.bintray.com/drummer-aidan/maven/com/afollestad/easyvideoplayer/

Temporarily you can add the lib this way, @DenisZhuravlev:

```gradle

    compile 'com.afollestad:easyvideoplayer:0.2.12'
    compile ('com.afollestad:material-camera:0.4.1') {
        exclude group: 'com.afollestad', module: 'easyvideoplayer'
    }
```

**Comment by afollestad** [comment]
Woops, it's published now.

https://bintray.com/drummer-aidan/maven/easy-video-player/0.2.13

**Comment by mowcixo** [comment]
Perfect. It should work now without changes @DenisZhuravlev.
