### ISSUE TITLE
Capturing video in portrait orientation (for ex.: 1080x1920)

### ISSUE THREAD

**Issue by ruha9005** [afollestad/material-camera#110]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Camera.
- [x] I have given my issue a non-generic title.

###### Information
 - Material Camera version: `0.4.1`
 - Device OS version: All
 - Device Manufacturer: All
 - Device Name: All

###### Reproduction Steps

1. Start MaterialCamera with `.videoPreferredAspect(16f / 9f)` and `.videoPreferredHeight(1080)`.
2. Capture video holding phone vertically.
3. See result.

###### Expected Result
Not rotated portrait oriented 1080x1920 video. Setting aspect 9f/16f and/or height 1920 doesn't do anything. FFmpegAndroid autorotates video to portrait when I use it (without specifying any rotatation option), but it takes much time. 

###### Actual Result
Rotated video '-90 degrees'.

**Comment by afollestad** [comment]
As the name of the method suggests, it gives a preferred aspect ratio. This library is only permitted to use aspect ratios and frame sizes that the device reports it supports; it will use the closest it can get to your preferred aspect ratio.
