### ISSUE TITLE
In stillshot mode, the image never actually updates after retrying

### ISSUE THREAD

**Issue by afollestad** [afollestad/material-camera#114]
If you take a stillshot image, click retry, and take another, the preview will show the first image.

**Comment by SniperDW** [comment]
I'm still having this issue, tested on Nexus 6P 7.0 and One Plus Two 6.0.
Any updates?

**Comment by tylerkrupicka** [comment]
Hey @SniperDW, you can see some other discussion here: https://github.com/afollestad/material-camera/issues/131. This bug is fixed in master, however the new build containing it (0.4.3) has not been packaged and released yet. Keep an eye out for that soon.

**Comment by SniperDW** [comment]
Excellent, thank you @tylerkrupicka!
