### ISSUE TITLE
Is that possible turning to snap photo mode?

### ISSUE THREAD

**Issue by waikchiu5** [afollestad/material-camera#12]
Thanks for your material camera.
I want to try new feature base on your application
However, i only need the snap photo mode.

Thanks

**Comment by afollestad** [comment]
Duplicate

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/issues/3

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/releases/tag/0.4.0

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/releases/tag/0.4.1
