### ISSUE TITLE
Screen Overlay problem in Marshmallow 

### ISSUE THREAD

**Issue by shafqatjamil** [afollestad/material-camera#122]
I am using your library for video recording its working fine but in my client device when she tries to record video its not working app says you need to turn off screen overlay. following is the link of video for problem
https://youtu.be/q2m_LNDdq2g

please help me I am stuck in this problem and i could not solve it i tried and searched a lot

**Comment by aguragorn** [comment]
She would need to close whatever app she has that overlays on the screen, for example fb messenger's floating chat bubble.

I would think this is a general marahmallow issue, especially when granting pernissions. An overlaying app may have control on anything beneath

**Comment by shafqatjamil** [comment]
yes that was it thanx for helping 👍
