### ISSUE TITLE
All the images are either long and thin in portrait mode or short and fat in horizontal.

### ISSUE THREAD

**Issue by sbmaggarwal** [afollestad/material-camera#147]
When I use MaterialCamera and it starts in the app, all the images are either long and thin in portrait mode or short and fat in horizontal. This can be observed when camera is on, even before taking any picture.

To confirm, just compare with device default camera.
![defaultcamera](https://cloud.githubusercontent.com/assets/6919017/20675217/8d701610-b5b1-11e6-8d4d-9c98efee94b2.png)
![materialcamera](https://cloud.githubusercontent.com/assets/6919017/20675218/8d70b7d2-b5b1-11e6-9f4b-c42ac0f48527.png)

**Comment by mdolnik** [comment]
Possible duplicate https://github.com/afollestad/material-camera/issues/90
