### ISSUE TITLE
Option to disable default icon tint

### ISSUE THREAD

**Issue by Spoetnic** [afollestad/material-camera#150]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [X] I have verified that I am using the latest version of Material Camera.
- [X] I have given my issue a non-generic title.

###### Include the following:
 - Material Camera version: `0.4.4`
 - Device OS version: `7.1`
 - Device Manufacturer: `Oneplus` / 'Asus'
 - Device Name: `One` / 'Nexus 7 (flo)'
 
###### Reproduction Steps

1. Use library as advertised
2. set 'iconRecord(R.drawable....)' in code

###### Expected Result
![image](https://cloud.githubusercontent.com/assets/490528/20982364/7d95716e-bcb8-11e6-9f18-123601555100.png)

###### Actual Result
![image](https://cloud.githubusercontent.com/assets/490528/20982377/8dceb95a-bcb8-11e6-9d5e-3ad88578063b.png)

The 'culprit' is here: :p
https://github.com/afollestad/material-camera/blob/cde4b0c3f3317445e6ebf3995022e7f417b833cf/library/src/main/java/com/afollestad/materialcamera/internal/BaseCameraFragment.java#L102

**Comment by afollestad** [comment]
As a design decision, I don't plan to allow disabling tinting.
