### ISSUE TITLE
Compression needed for photo capture

### ISSUE THREAD

**Issue by gabbimark** [afollestad/material-camera#158]
- [x ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x ] I have verified that I am using the latest version of Material Camera.
- [x ] I have given my issue a non-generic title.

 - Material Camera version: latest
 - Device OS version: `all
 - Device Manufacturer: `all
 - Device Name: all

Hi i am noticing file sizes of around 2mb when i capture using certain devices. Is there a setting to compress the photo or is there any work around for this? these photos are stored and server and currently photo sizes are way to large.  

Thanks, 
Mark G.

**Comment by tylerkrupicka** [comment]
hey @gabbimark, I'm thinking that adding quality profile support shown in the https://github.com/afollestad/material-camera/issues/141 ticket would probably be what you're looking for, as it would reduce the size of images. I'm going to close this issue for now and recommend following that ticket, but if you don't think that solution will address your problem then I can look into reopening it.

Thanks!
