### ISSUE TITLE
Image flip issue in front camera 

### ISSUE THREAD

**Issue by surinder97815** [afollestad/material-camera#162]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Camera.
- [ ] I have given my issue a non-generic title.

###### Include the following:
 - Material Camera version: `0.2.13`
 - Device OS version: `4.1.2`
 - Device Manufacturer: `Samsung`
 - Device Name: `GT 7582`

I am trying to capture image using the front camera but after result image comes flipped.

for  eg  on image capture time if object   looks  ABC   and in image it's looks like CBA

**Comment by tylerkrupicka** [comment]
Are you referring to the same behavior described in https://github.com/afollestad/material-camera/issues/112? Flipping the front facing image is the default behavior of Google's camera app.
