### ISSUE TITLE
Not letting import the material camera in Gradle because of easyVideoPlayer.

### ISSUE THREAD

**Issue by gauravchandra19** [afollestad/material-camera#164]
- Material Camera version: `0.4.4`
 
I'm trying to import the material camera library in dependency of studio but it is giving me the following error on syncing.
Error:Could not GET 'https://jitpack.io/com/afollestad/easyvideoplayer/0.3.0/easyvideoplayer-0.3.0.pom'. Received status code 401 from server: Unauthorized
<a href="toggle.offline.mode">Enable Gradle 'offline mode' and sync project</a>
###### Reproduction Steps

1. Just sync the project after pasting the compile line.

**Comment by afollestad** [comment]
It's because it's trying to use JitPack. It's hosted on jCenter, not JitPack.
