### ISSUE TITLE
To make background camera recorder using material-camera 

### ISSUE THREAD

**Issue by vinod1988** [afollestad/material-camera#166]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Camera.
- [x] I have given my issue a non-generic title.

###### Include the following:
 - Material Camera version: `0.2.13`
 - Device OS version: `7.0`
 - Device Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`

Also, please wrap Java with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```
 
###### Reproduction Steps

1. 
2. 
3. 

###### Expected Result
on camera start button click it should record the video while i switch the phone off screen. It should not be closed a video. I want to be continue unless until i will stop the camera recording.

**Comment by afollestad** [comment]
That's out of scope for this library, and is not very practical because of how Android's Activity life cycle works.
