### ISSUE TITLE
This error occurred on the android4.4.2 system tablet (screen size 10.1 inches).

### ISSUE THREAD

**Issue by generalzou** [afollestad/material-camera#17]
![screenshot_2013-06-04-14-06-11](https://cloud.githubusercontent.com/assets/7219905/12486863/775e3b52-c09f-11e5-8e5f-1f2efd34684e.png)
![screenshot_2013-06-04-14-05-37](https://cloud.githubusercontent.com/assets/7219905/12486877/861a8dc6-c09f-11e5-9612-96d10a0d5a86.png)

**Comment by afollestad** [comment]
There isn't enough information here to have an issue.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/releases/tag/0.2.2
