### ISSUE TITLE
Audio is played first before the video

### ISSUE THREAD

**Issue by Dyoed** [afollestad/material-camera#170]
- [X] I have verified there are no duplicate active or recent bugs, questions, or requests
- [X] I have verified that I am using the latest version of Material Camera.
- [X] I have given my issue a non-generic title.

###### Include the following:
 - Material Camera version: `0.4.4`
 - Device OS version: `7.0`
 - Device Manufacturer: `Samsung`
 - Device Name: `S6`

Video captured becomes 2x longer, the first half, the video and still and the audio is played. The second half, only the video is played
 
When I try recording with audio disabled, the problem doesn't occur.

**Comment by Dyoed** [comment]
It seems like a device problem, I restarted the phone and it no longer occurs.

**Comment by wu16hk** [comment]
I have the same problem as you.
