### ISSUE TITLE
.SaveDir(File) Shows Error

### ISSUE THREAD

**Issue by taimoorsuleman** [afollestad/material-camera#173]
After Clicking on Use Video i got this error.
Failed to upload: 1 due to Unable to calculate MD5 hash: /: open failed: EISDIR (Is a directory)                                             
                                               [ 03-27 17:27:55.648 22717:22717 I/         ]
                                               onError: Unable to calculate MD5 hash: /: open failed: EISDIR (Is a directory)
Note.I have enable write permission as well.
Deivce:Nexus 5

**Comment by afollestad** [comment]
Looks like you're trying to save a file with a name that matches an existing directory (the root directory).
