### ISSUE TITLE
Failed to Resolve com.afollestad.easyvideoplayer:0.3.0

### ISSUE THREAD

**Issue by ahsanic** [afollestad/material-camera#187]
I am having the following error in the gradle.

Failed to resolve : com.afollestad.easyvideoplayer:0.3.0

**Comment by shruti8597** [comment]
repositories {
    jcenter()
    maven { url "https://dl.bintray.com/drummer-aidan/maven" }
}

Add this in Module build.gradle rather than in project.

**Comment by ahsanic** [comment]
Works Like charm! Thanks!
