### ISSUE TITLE
video is distorted  

### ISSUE THREAD

**Issue by joomi** [afollestad/material-camera#19]
Hi Aidan 
First I must say you did a great job, it looks really good, thanks.
Trying it out, I find that the videos are distorted and lost their original scale.
I wonder if you encounter this issue.
Im using LG G3
android version 5

**Comment by EzequielAdrianM** [comment]
I've experienced distorted video while recording ONLY with Front camera. But It is only on the recording preview, since the saved video is fine. Also this only happens in Portrait mode.

**Comment by joomi** [comment]
In my case it's also in the saved video, not just preview

**Comment by lezardos** [comment]
The preview is distorted on Nexus 4 as well.
Regards

**Comment by afollestad** [comment]
0.2.5 should help.

https://github.com/afollestad/material-camera/releases/tag/0.2.5
