### ISSUE TITLE
Is there a way to use 

### ISSUE THREAD

**Issue by AviadKlein10** [afollestad/material-camera#195]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Camera.
- [x] I have given my issue a non-generic title.

Hi I can't use this 
 .lengthLimitSeconds(10)

is there any other way to limit record time?

**Comment by tylerkrupicka** [comment]
@AviadKlein10 can you explain why you can't use the normal API?
