### ISSUE TITLE
Build finished with Errors.

### ISSUE THREAD

**Issue by EzequielAdrianM** [afollestad/material-camera#24]
When I add all your dependencies to my Project causes the following error:

    ...\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.2.0\res\values-v23\values-v23.xml
    Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
    Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.

My project compileSdkVersion is 22 and buildtoolsversion is 22.0.1 and targetSdkVersion is 22.
MinSdkversion is 15.

**Comment by afollestad** [comment]
You need to use AppCompat 23.2.0 in your app.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/releases/tag/0.2.2
