### ISSUE TITLE
Samsung galaxy J2 issue

### ISSUE THREAD

**Issue by vishal-200985** [afollestad/material-camera#27]
Hello Sir ... This is little urgent .... I have implemented your Material Camera project in my Application ... But issue i am facing in Samsung galaxy J2 .. i am not able to open front camera ... its showing black screen.. Please help me ..
You can revert me at my mail id : vishu.sharma899@gmail.com

**Comment by afollestad** [comment]
Emails aren't used with issue tracking.

There's not much I can unfortunately, Samsung issues tend to have a lot of random issues. Hopefully the next release fixes it.
