### ISSUE TITLE
Add support for still image capture

### ISSUE THREAD

**Issue by tuhin10** [afollestad/material-camera#3]

**Comment by anvesh523** [comment]
Good one. 
 Suggestion for Image capture too ..... with 1:1 aspect ratio. It's very useful for all.

**Comment by pizza** [comment]
+1

**Comment by vanshg** [comment]
+1

**Comment by LetaiefAymen** [comment]
+1

**Comment by edwinkr2000** [comment]
+1

**Comment by vanshg** [comment]
@afollestad Is there any intention of making this happen? If not, I will explore other options I have, but it would be great if everything was in one library

**Comment by ritdaw** [comment]
+1

**Comment by minimalviking** [comment]
+1

**Comment by afaucogney** [comment]
+1

**Comment by joomi** [comment]
+1

**Comment by bicho** [comment]
+1

**Comment by pengjianbo** [comment]
+1

**Comment by Mardoqueu** [comment]
+1

**Comment by rephiscorth** [comment]
+1

**Comment by tomiu** [comment]
@afollestad
I can do that have had lots of experience of creating my own custom camera app already.

**Comment by afollestad** [comment]
@tomiu that would be great, please test it as much as possible though.

This library was initially created for use in one of my employer's apps, so I don't want to break anything 😁

**Comment by tomiu** [comment]
@afollestad Is there a reason that Camera2 is disabled by default?
Check CameraUtil, line 58

**Comment by Sebas7ien** [comment]
+1 to take picture too

**Comment by danielchristopher1** [comment]
+1

**Comment by tomiu** [comment]
There's a fork here, with stillshot implemented:
https://github.com/tomiu/material-camera

**Comment by tylerkrupicka** [comment]
+1

**Comment by sugarmanz** [comment]
+1

**Comment by afollestad** [comment]
I wouldn't recommend using that fork above since it is so outdated.

**Comment by XiaolongQiao** [comment]
During the video recording, the picture is drawn. How to set

**Comment by mowcixo** [comment]
@afollestad As I say in PR #70, I updated the @tomiu fork to the latest changes in master, added doc, and I think is a good idea to implement this PR, because is non intrusive and well made.

**Comment by sugarmanz** [comment]
@afollestad: The still shot PR (#70) has since been tested by @tylerkrupicka and I. With our various bug fixes and @mowcixo s work updating the @tomiu fork, we have added still shot as a stable feature. More info #70].

**Comment by afollestad** [comment]
In the latest release.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/releases/tag/0.4.0

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/releases/tag/0.4.1
