### ISSUE TITLE
Add method setProfile(CamcorderProfile)

### ISSUE THREAD

**Issue by ruha9005** [afollestad/material-camera#32]
Add methods from [http://developer.android.com/intl/ru/reference/android/media/CamcorderProfile.html#audioBitRate](url)
and `setMaxAllowFileSize`
And fix `MaterialCamera(this).videoPreferredHeight(...)`, it doesn't work like it must work.

**Comment by afollestad** [comment]
@ruha9005 `videoPreferredHeight()` works as intended. Android devices have a limited set of resolutions that they support, you can force a specific size of aspect ratio.

I will add `setMaxAllowFileSize`, though.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/releases/tag/0.2.4
