### ISSUE TITLE
Requested frame rate(30) is not supported: 5,10,15,24 start failed - 19

### ISSUE THREAD

**Issue by yilzer** [afollestad/material-camera#33]
Requested frame rate(30) is not supported: 5,10,15,24
start failed - 19

samsung i9104 Galaxy S II Plus
Os: Android 4.2.2
api level: 17
screen: 480 x 800 px |hdpi|4.3"

I got this error when testing on this device. The back camera worked fine but the front camera
crashes with this error. Can this be resolved by setting a lower standard frame rate? Or wil give this errors on other devices.

Yilzer

**Comment by afollestad** [comment]
You can pretty easily change that setting, but I changed the default.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/releases/tag/0.2.4
