### ISSUE TITLE
Video playback can only be played once again, once again hit the player can not play.

### ISSUE THREAD

**Issue by dalong982242260** [afollestad/material-camera#34]
Video playback can only be played once again, once again hit the player can not play.

**Comment by afollestad** [comment]
Resolved with newer versions, it was due to a bug in ExoMedia.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/releases/tag/0.2.4

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/releases/tag/0.4.0

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/releases/tag/0.4.1
