### ISSUE TITLE
Saving picture is too slow. 

### ISSUE THREAD

**Issue by lowfiend** [afollestad/material-camera#36]
03-30 16:38:21.299 5223-8165/System.out: Took 13.653 seconds to write 500,043,780 bytes
03-30 16:38:21.300 5223-8165/System.out: Took 0.002 seconds to close
03-30 16:38:21.308 5223-5223/takeStillShot: picture saved to disk - jpeg, size: 138210

It let user wait 14 seconds then change layout.
How can I reduce time?

**Comment by afollestad** [comment]
That method doesn't exist in this library (there is no still capture), so I'm not sure what you're referring to.
