### ISSUE TITLE
Aspect Ratio 1:1

### ISSUE THREAD

**Issue by JorgeBazarte** [afollestad/material-camera#42]
First, Great Job!!
How can I set an aspect ratio 1:1? I've been trying with different configuration but always fails and give me a file with the next qualities, 176x144.
I'm developing an app that includes small videos (15 seconds)

**Comment by ruha9005** [comment]
try it:
`.videoPreferredAspect(1f / 1f)`

**Comment by gouravd** [comment]
I do not think this will work, without significant changes to the source. According to the current source, only supported Aspect ratios by the android device (like 3:4 and 9:16) will work.

**Comment by afollestad** [comment]
There is no way to force a specific aspect ratio, thus why you can only set a "preferred" aspect ratio. 

If you use an aspect ratio or output size not reported as "supported" by the device, your app will crash.
