### ISSUE TITLE
CameraUtil.hasCamera2 API judge issue

### ISSUE THREAD

**Issue by puyanlin** [afollestad/material-camera#44]
```
final CameraCharacteristics characteristics = manager.getCameraCharacteristics(str);
final int supportLevel = characteristics.get(CameraCharacteristics.INFO_SUPPORTED_HARDWARE_LEVEL);
if (supportLevel == CameraCharacteristics.INFO_SUPPORTED_HARDWARE_LEVEL_LEGACY) {
       notNull = false;
       break;
}

```
there is a problem in the 'if' statement, some old but updatable devices just support Camera2 API, but its system parameter just match 'supportLevel == CameraCharacteristics.INFO_SUPPORTED_HARDWARE_LEVEL_LEGACY' condition, so they would use incorrect ratio old camera API... ex: Nexus 4/Nexus 7(2rd-gen)...

**Comment by puyanlin** [comment]
why add these code back in v 0.2.6?

**Comment by afollestad** [comment]
The change that removed it broke a lot for other devices.

On Tue, May 10, 2016, 12:42 PM Joseph Lin <notifications@github.com> wrote:

> why add these code back in v 0.2.6?
>
> —
> You are receiving this because you modified the open/close state.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/afollestad/material-camera/issues/44#issuecomment-218234462>
>
-- 

Regards,

Aidan Follestad
http://aidanfollestad.com
651-528-1662
