### ISSUE TITLE
Error:Camera is already in use

### ISSUE THREAD

**Issue by dalong982242260** [afollestad/material-camera#45]
The latest editor to run the error  ：Camera is already in use

**Comment by puyanlin** [comment]
I set `.autoSubmit(true)` to avoid this error yet

**Comment by jayshah123** [comment]
+1 seen in sample app in Note4 - 6.0.1

**Comment by jayshah123** [comment]
Camera2 seems to be the culprit. : for fallback behaviour : `.forCamera(true)` can probably be used.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/releases/tag/0.2.6
