### ISSUE TITLE
Error - MediaRecorder start error.

### ISSUE THREAD

**Issue by ush-gan** [afollestad/material-camera#47]
Hi,

I am getting a E/MediaRecorder: start failed: -19 when I used the sample application. java.lang.RuntimeException: start failed in CameraFragment line 360. I could see the MaterialCamera folder created and the file VID_20160425_170338.mp4 created with 0 bytes.

This is on Samsung S3, Android Version 4.3.  I have the latest SDK, support library 23.3.0. Can you please let me know if I have missed out any steps.

Thanks.

Rgds,
Ganesh

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/releases/tag/0.2.6
