### ISSUE TITLE
It closes immediately when i press the record button.

### ISSUE THREAD

**Issue by uzman** [afollestad/material-camera#50]
hi,
i tried with latest (0.2.5) and 0.2.4 but there is weird bug. it closes the camera immediately if i press the record button. but there is no crash.
it can be related with output format.

Device: Samsung S3 + v 4.4.2

settings:

```java
new MaterialCamera(this)
        .saveDir(saveDir)
        .defaultToFrontFacing(true)
        .showPortraitWarning(false)
        .autoSubmit(true)
        .allowRetry(false)
        .countdownSeconds(30f)
        .countdownImmediately(false)
        .primaryColorAttr(R.attr.colorPrimary)
        .start(CAMERA_RQ);
```

logcat:

```Gradle
E/MediaRecorder: start failed: -19
java.lang.RuntimeException: start failed.
    at android.media.MediaRecorder.start(Native Method)
    at com.afollestad.materialcamera.internal.CameraFragment.startRecordingVideo(CameraFragment.java:360)
    at com.afollestad.materialcamera.internal.CameraFragment.onClick(CameraFragment.java:133)
    at android.view.View.performClick(View.java:4640)
```

**Comment by uzman** [comment]
i found it.
frame rate must be set.
                .videoFrameRate(30)

it works now. but there is still same bug. pressing back button freezes the app while recording. 
(https://github.com/afollestad/material-camera/issues/39)

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/releases/tag/0.2.6
