### ISSUE TITLE
Delay recording start

### ISSUE THREAD

**Issue by upta** [afollestad/material-camera#54]
I was curious if you had any thoughts/ideas on including an option for doing a countdown delay before recording starts?  Maybe something where the user could pick how many seconds of a delay?

Thanks for the insight!

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/releases/tag/0.4.0

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/releases/tag/0.4.1
