### ISSUE TITLE
401 error

### ISSUE THREAD

**Issue by IFDeveloper** [afollestad/material-camera#55]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Camera.
- [x] I have given my issue a non-generic title.

compile 'com.afollestad:material-camera:0.2.12' 
results in :
Error:Could not GET 'https://jitpack.io/com/afollestad/easyvideoplayer/0.2.6/easyvideoplayer-0.2.6.pom'. Received status code 401 from server: Repo not found or no access token provided

executing direct GET request asks for login and password :D

**Comment by tbarsbay** [comment]
I'm having this issue as well.

**Comment by afollestad** [comment]
The library isn't on JitPack, it's on jCenter and Bintray.

**Comment by afollestad** [comment]
See the README.

**Comment by tbarsbay** [comment]
I'm using jcenter in my build file but still receiving the error described.

**Comment by afollestad** [comment]
See https://github.com/afollestad/material-camera/issues/56

**Comment by IFDeveloper** [comment]
issue solved
pls add 
maven { url "https://dl.bintray.com/drummer-aidan/maven" } to README file 
since dependency is not so obvious. thx

**Comment by afollestad** [comment]
I won't add it to the README, that's only a work around. Not a solution to why it's not resolving from jCenter correctly.

**Comment by IFDeveloper** [comment]
ok, w8ing for solution, thx anyway

**Comment by amouly** [comment]
Same issue for me, with latest build tools and Studio versions. Fixed with @IFDeveloper comment.

**Comment by Sateesh2** [comment]
still getting 401 error
