### ISSUE TITLE
Failed to resolve: com.afollestad:easyvideoplayer:0.2.6

### ISSUE THREAD

**Issue by shalevmo** [afollestad/material-camera#56]
I'm trying to import the library, and i'm getting:
Error:Failed to resolve: com.afollestad:easyvideoplayer:0.2.6

adding this:

```gradle
maven { url "https://dl.bintray.com/drummer-aidan/maven" }
```

to my repositories seem to solve it, but I don't think it is supposed be like that.

**Comment by emanuelet** [comment]
the repo com.afollestad:easyvideoplayer needs the new release number

**Comment by afollestad** [comment]
Please try the latest release.
