### ISSUE TITLE
Not able to download library via Jitpack IO repository

### ISSUE THREAD

**Issue by jd-alexander** [afollestad/material-camera#6]
Followed the instructions to add your library to my project but not able to download it. 

![screenshot_2015-12-01-15-28-20](https://cloud.githubusercontent.com/assets/1509205/11513231/fff44e62-983f-11e5-8f36-77c8c9b399f1.png)

**Comment by afollestad** [comment]
Well, the library is working fine for me, and JitPack reports that it built successfully: https://jitpack.io/#afollestad/material-camera

You might want to report an issue to JitPack here: https://github.com/jitpack/jitpack.io/issues

**Comment by osflor** [comment]
I had the same problems at first until I realized there seems to be a tiny mistake in the instructions. They say: 
  compile('com.github.afollestad.material-camera:0.1.1@aar')
When it should probably be: 
  compile('com.github.afollestad:material-camera:0.1.1@aar') 
So just change the '**.**' to a '**:**' before the repo name and it works fine.

**Comment by jd-alexander** [comment]
Oh thanks. I went through all the trouble of manually downloading the lib and adding it as a module.Glad I can go back to the normal way. :+1:

**Comment by afollestad** [comment]
I also discovered the JitPack repository generally has to go in your root build.gradle file, rather than your module build.gradle file

**Comment by jd-alexander** [comment]
Okay. The naming change of the compile statement you made to the readme
fixed it for me.
