### ISSUE TITLE
Not able to playback the recording after countdownSeconds is reached

### ISSUE THREAD

**Issue by shireen028** [afollestad/material-camera#60]
Hi,
I'm working on the example app but I cant playback the recording in one case. The video after it reaches 30 seconds countdown, it gets submitted even when autoSubmit is set to false. Is there something missing? 

Device: LG Nexus 5 + v6.0.1 & HTC M8 + v4.4.2 
Material Camera version: 0.2.13
These are my settings

```java
new MaterialCamera(this)
                .saveDir(saveDir)
                .showPortraitWarning(false)
                .defaultToFrontFacing(false)
                .qualityProfile(MaterialCamera.QUALITY_LOW)
                .maxAllowedFileSize(15 * 1024 * 1024)
                .countdownSeconds(30)
                .allowRetry(true)
                .autoSubmit(false)
                .start(CAMERA_RQ);
```

**Comment by BackPackerDz** [comment]
I have the same issue, how did you solve it ?

**Comment by UglyTroLL** [comment]
@shireen028 Were you able to figure it out? I have the same issue here

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/releases/tag/0.4.0

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/releases/tag/0.4.1
