### ISSUE TITLE
Low video quality

### ISSUE THREAD

**Issue by Max0n** [afollestad/material-camera#62]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Camera.
- [x] I have given my issue a non-generic title.

###### Include the following:
 - Material Camera version: `0.2.13`
 - Device OS version: `5.1`
 - Device Manufacturer: `Meizu`
 - Device Name: `m2 note`

The video quality was low. Then I just modified a part of the MainActivity.java but it has not given the results. Here is this part before:
```java
        new MaterialCamera(this)
                .saveDir(saveDir)
                .showPortraitWarning(true)
                .allowRetry(true)
                .defaultToFrontFacing(false)
```
after:
```java
        new MaterialCamera(this)
                .saveDir(saveDir)
                .showPortraitWarning(true)
                .allowRetry(true)
                .defaultToFrontFacing(false)
                .videoEncodingBitRate(9000000)
                .audioEncodingBitRate(3200000)
                .videoFrameRate(60)
                .videoPreferredHeight(4000)
                .start(CAMERA_RQ);
```
This video from Material Camera: http://s1079.photobucket.com/user/icrafter/media/VID_20160605_143105_zpswwm4jzng.mp4.html?o=0
This one from stock camera app : http://s1079.photobucket.com/user/icrafter/media/V60605-145230_zpsqps6lluq.mp4.html

**Comment by sfilmak** [comment]
You need to open BaseCaptureActivity.java in Material Camera Library and change video preferred aspect from 4f / 3f to 16f / 9f.

**Comment by Max0n** [comment]
Maybe in MainActivity.java not in BaseCaptureActivity.java? I can't find video preferred activity in this but it's in MainActivity.java.

**Comment by Max0n** [comment]
... And it has not given result too. Video becomes blinking and quality becomes grainy. I hope you understand me because I'm Russian and bad speak English.

**Comment by sfilmak** [comment]
Тогда, пожалуй, нам лучше перейти на русский

**Comment by sfilmak** [comment]
Нет, все верно, эту строчку можно найти в файле BaseCaptureActivity:

`  @Override
    public float videoPreferredAspect() {
        return getIntent().getFloatExtra(CameraIntentKey.VIDEO_PREFERRED_ASPECT, 4f / 3f);
    }

    @Override
    public int videoPreferredHeight() {
        return getIntent().getIntExtra(CameraIntentKey.VIDEO_PREFERRED_HEIGHT, 720);
    }`

**Comment by Max0n** [comment]
Строчку-то нашел. Поменял аспект на 16 / 9 и качество с 720 на 1080p. Но результата не дало. Видео зернистое и нет фокусировки.

**Comment by sfilmak** [comment]
Попробуйте убрать из MainActivity все дополнительные настройки и вернуть все к начальному состоянию:
`new MaterialCamera(this)
                .saveDir(saveDir)
                .showPortraitWarning(true)
                .allowRetry(true)
                .defaultToFrontFacing(false)`
Если не поможет, то, увы, ничем больше помочь не могу. У меня на Xiaomi Mi3 с Android 6.0 (AOSP) изменение соотношения сторон решило проблему качества.

**Comment by Max0n** [comment]
Ситуация стала буквально чуть-чуть лучше, но зернистость по сравнению со стоковой камерой все же присутствует и это сильно портит качество. Спасибо за совет, надеюсь разработчик обратит внимание на проблему и исправит ее.
