### ISSUE TITLE
The ability to start recording immediately when the camera opens

### ISSUE THREAD

**Issue by ruudschouten** [afollestad/material-camera#65]
- [ x ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ x ] I have verified that I am using the latest version of Material Camera.
- [ x ] I have given my issue a non-generic title.

 - Material Camera version: `0.2.13`
 - Device OS version: `6.0`
 - Device Manufacturer: `Motorola`
 - Device Name: `Moto G 2014 LTE`

I was wondering if it was possible to start recording as soon as the camera intent is started. I need to be able to do this because I want to start recording when I get a push notification from a server.

**Comment by afollestad** [comment]
This is possible in the latest release if you set autoRecordingWithDelayMs(0)
