### ISSUE TITLE
Failed to resolve: com.afollestad:easyvideoplayer:0.2.8

### ISSUE THREAD

**Issue by atf1999** [afollestad/material-camera#69]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Camera.
- [x] I have given my issue a non-generic title.

 - Material Camera version: `0.2.14`
 - Device OS version: `4.4.2`
 - Device Manufacturer: `Samsung`
 - Device Name: `Galaxy S3 Mini`

When I compile my project with Material Camera as a dependency, I get the error above. Here is my gradle dependencies:
```gradle
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'com.afollestad:material-camera:0.2.14'

}
```

**Comment by afollestad** [comment]
There we duplicate issues.

https://github.com/afollestad/material-camera/issues/56
