### ISSUE TITLE
Failed gradle dependency

### ISSUE THREAD

**Issue by ManicMapple** [afollestad/material-camera#7]
Hi,
I followed your description in the readme, but when I want to build the app I get 

> Error:Failed to resolve: com.github.afollestad.material-camera:0.1.1:

It does also not work if i use 
https://jitpack.io/#afollestad/material-camera/0.1.1

I tripple checked my build gradle, thats fine.

I use android studio.

**Comment by afollestad** [comment]
See the closed issue

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/issues/6

**Comment by afollestad** [comment]
@ManicMapple see the updated README, the repository needs to go in your application-level (rather than module-level) build.gradle file, under `allprojects`

**Comment by ManicMapple** [comment]
Great, thanks a lot
