### ISSUE TITLE
Sometimes crashes while recording on Nexus 5x

### ISSUE THREAD

**Issue by RockyLin** [afollestad/material-camera#76]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Camera.
- [x] I have given my issue a non-generic title.

###### Include the following:
 - Material Camera version: `0.2.13`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `LG`
 - Device Name: `Nexus 5X`

 
###### Reproduction Steps

1. open camera
2. record

###### Expected Result
works fun while recording

###### Actual Result
sometimes, it crashes while recording without crash message(eg. Fatal...) which makes it hard to debug....

**Comment by afollestad** [comment]
There's not enough info to make an issue here.
