### ISSUE TITLE
Preview video screen crashing

### ISSUE THREAD

**Issue by jdamacena** [afollestad/material-camera#81]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Camera.
- [x] I have given my issue a non-generic title.

###### Include the following:
 - Material Camera version: `0.2.14`
 - Device OS Android version: `6.0`
 - Device Manufacturer: `Motorola`
 - Device Name: `Moto G2 XT1069`
 
###### Reproduction Steps

1. Start Material Camera with "autoSubmit(false)"
2. Take a video

###### Expected Result

After recording, the preview screens opens to play the recorded video.

###### Actual Result

After recording, the Material Camera crashes due to an error on the formatter.
![2016-08-19_164849](https://cloud.githubusercontent.com/assets/19500428/17822321/d8c08e62-662c-11e6-8ba2-5340de9f0bf0.png)

**Comment by afollestad** [comment]
Should be fixed in the newer release.
