### ISSUE TITLE
Playback skipped when using countdownSeconds and autoSubmit(false)

### ISSUE THREAD

**Issue by BackPackerDz** [afollestad/material-camera#84]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Camera.
- [ ] I have given my issue a non-generic title.

###### Include the following:
 - Material Camera version: `0.3.0`
 - Device OS version: `4.2`
 - Device Manufacturer: `Huawei`
 - Device Name: `Huawei P6`

Also, please wrap Java with correct syntax highlighting.

```java
  MaterialCamera materialCamera = new MaterialCamera(this)
                .saveDir(saveDir)
                .showPortraitWarning(false)
                .countdownSeconds(2)
                .allowRetry(true)
                .autoSubmit(false)
                .defaultToFrontFacing(true)
```
###### Expected Result
When I use ".countdownSeconds", the demo doesnt' send me to the playback part !

**Comment by UglyTroLL** [comment]
+1 Same issue here

**Comment by aelimill** [comment]
same issue

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/releases/tag/0.4.0

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/releases/tag/0.4.1
