### ISSUE TITLE
Its giving me this error "Error:Failed to resolve: com.afollestad:easyvideoplayer:0.2.11"

### ISSUE THREAD

**Issue by shafqatjamil** [afollestad/material-camera#88]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of Material Camera.
- [ ] I have given my issue a non-generic title.

###### Include the following:
 - Material Camera version: `0.2.13`
 - Device OS version: `7.0`
 - Device Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`

Also, please wrap Java with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```
 
###### Reproduction Steps

1. 
2. 
3.

**Comment by afollestad** [comment]
There are countless duplicates.
