### ISSUE TITLE
Time limit after beginning recording

### ISSUE THREAD

**Issue by osflor** [afollestad/material-camera#9]
Hi when I try to set a time limit for the video the countdown starts immediately, even before I press the record button. Is this the intended behavior? 

My code is:

```java
new MaterialCamera(this)
                        .saveDir(saveFolder)
                        .primaryColorAttr(R.attr.colorPrimary)
                        .showPortraitWarning(true)
                        .autoSubmit(false)
                        .defaultToFrontFacing(false)
                        .lengthLimitSeconds(10)
                        .start(REQUEST_VIDEO);
```

**Comment by afollestad** [comment]
Currently, it is, because of how the library is used in one of my employer's apps. I can add a setting to change the behavior.

**Comment by osflor** [comment]
If you ever do that that would be great. Btw thanks for an awesome library.

**Comment by afollestad** [comment]
When the next update is available, it will work like this:

```java
new MaterialCamera(this)
    .countdownMinutes(2.5f)
    .countdownImmediately(true)
    .start(CAMERA_RQ);
```

If you don't use `countdownImmediately(true)`, it will wait until the user presses 'Record' to start the countdown.
