### ISSUE TITLE
Make 'use stillshot' label configurable like 'use video'

### ISSUE THREAD

**Issue by aguragorn** [afollestad/material-camera#94]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Camera.
- [x] I have given my issue a non-generic title.

Material Camera Version: 0.3.2

**Comment by mowcixo** [comment]
This is fixed in the master branch, no tag yet though.

You can do it by using the new ```.labelConfirm()``` method, ```.labelUseVideo()``` is marked as deprecated.

**Comment by aguragorn** [comment]
Thanks. I'd be closing this issue then.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/releases/tag/0.4.0

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/releases/tag/0.4.1
